# Chapter 4 The Standard Deviation and Other Measures of Dispersion

Part 1

## Dispersion, or variation
The degree to which numerical data tend to spread about an average value is called the _dispersion_, or _variation_, of the data. Various measures of this dispersion (or variation) are available, the most common being the range, mean deviation, semi-interquartile reange, $10$&mdash;$90$ percentile range, and standard deviation.

---

## The Range
The _range_ of a set of numbers is the difference between the largest and smallest numbers in the set.

---

__EXAMPLE 1.__ The range of the set $2, 3, 3, 5, 5, 5, 8, 10, 12$ is $12-2=10$. Sometimes the range is given by simply quoting the smallest and largest numbers; in the above set, for instance, the range could be indicated as $2$ to $12$, or $2-12$.

---

__4.1.__ Find the range of the sets (a) 12, 6, 7, 3, 15, 10, 18, 5 and (b) 9, 3, 8, 8, 9, 8, 9, 18

### Solution
In both cases, range $=$ largest number $-$ smallest number $=18-3=15$. However, as seen from the arrays of sets (a) and (b),<p>
$$
\begin{align*}
\text{(a)}\ 3, 5, 6, 7, 10, 12, 15, 18\ \ \ \ \ \ \ \ \text{(b)}\ 3, 8, 8, 9, 9, 9, 18
\end{align*}
$$<p>
there is much more variation or dispersion, in (a) than in (b). In fact, (b) consists mainly of $8$'s and $9$'s.<p>
Since the range indicates no difference between the sets, it is not a very good measure of dpsersion in this case. Where extreme values are present, the range is generally a poor measure of dispersion.<p>
An improvement is achieved by throwing out the extreme cases, $3$, and $18$. Then for set (a) the range is $(15 - 5) = 10$, while for set (b) the range is $(9-8)=1$, clearly showing that (a) has greater dispersion than (b). However, this is not the way the range is defined. The semi-interquartile range and the 10&mdash;90 percentile range were designed to improve on the range by eliminating extreme cases.

In [1]:
p1.a <- c(12, 6, 7, 3, 15, 10, 18, 5)
p1.b <- c(9, 3, 8, 8, 9, 8, 9, 18)
(p1.a.range <- diff(range(p1.a)))
(p1.b.range <- diff(range(p1.b)))

[1] 15

[1] 15

---

__4.2.__ Find the range of heights of the students at XYZ University. 

In [2]:
load("Saves/Table_2.1.Rdata")
Table_2.1

60-62,5
63-65,18
66-68,42
69-71,27
72-74,8


### Solution
There are two ways of defining the range for grouped data.
#### First method
$$
\begin{align*}
\text{Range}=\text{class mark of highest class}-\text{class mark of lowest class}=73-61=12\text{in}
\end{align*}
$$
#### Second method
$$
\begin{align*}
\text{Range}=\text{upper class boundary of highest class}-\text{lower class boundary of lowest class}=74.5-59.5=15\text{in}
\end{align*}
$$<p>
The first method tends to eliminate extreme cases to some extent.

In [3]:
# First method - use class marks
# This method tends to eliminate extreme cases to some extent
p2.marks <- c(61, 64, 67, 70, 73)
(p2.xyz.mark.range <- diff(range(p2.marks)))

[1] 12

In [4]:
# Second method - use class boundaries
p2.boundaries <- c(59.5, 62.5, 65.5, 68.5, 71.5, 74.5)
(p2.xyz.boundary.range <- diff(range(p2.boundaries)))

[1] 15

---

## The mean deviation
The _mean deviation_, or _average deviation_, of a set of $N$ numbers $X_1, X_2,\ldots,X_N$ is abbreviaged $\text{MD}$ and is defined.<p>
\begin{align}
\text{MD}
= \frac{\sum^N_{j=1}{\lvert X_j-\bar{X}\rvert}}{N}
= \frac{\sum{\lvert X-\bar{X}\rvert}}{N}
= \frac{\sum{|X - \bar{X}|}}{N}
= \overline{\lvert X-\bar{X}\rvert}\label{eq1}\tag{1}
\end{align}<P>
where $\bar{X}$ is the arithmetic mean of the numbers and $\lvert X_j-\bar{X}\rvert$ is the absolute value of the deviation of $X_j$ from $\bar{X}$. (The _absolute value_ of a number is the number without the associated sign and is indicated by two vertical lines placed around the number; thus $\lvert-4\rvert=4,\lvert+3\rvert=3,\lvert6\rvert=6,$ and $\vert-0.84\rvert=0.84$.)<p>
__EXAMPLE 2.__  Find the mean deviation of the set $2, 3, 6, 8, 11$.<p>
\begin{align}
\text{Arithmetic mean (}\bar{X}\text{)}=\frac{2+3+6+8+11}{5}=6
\end{align}<p>
\begin{align}
\text{MD}
=\frac{\lvert2-6\rvert+\lvert3-6\rvert+\lvert6-6\rvert+\lvert8-6\rvert+\lvert11-6\rvert}{5}
=\frac{\lvert-4\rvert+\lvert-3\rvert+\lvert0\rvert+\lvert2\rvert+\lvert5\rvert}{5}
=\frac{4+3+0+2+5}{5}=2.8
\end{align}<p>
If $X_1, X_2,\ldots,X_K$ occur with frequencies $f_1,f_2,\ldots,f_K$, respectively, the mean deviation can be written as<p>
\begin{align}
\text{MD}
=\frac{\sum^K_{j=1}{f_j\lvert X_j-\bar{X}\rvert}}{N}
=\frac{\sum{f\lvert X-\bar{X}\rvert}}{N}
=\overline{\lvert X-\bar{X}\rvert}\label{eq2}\tag{2}
\end{align}<p>
where $N=\sum^K_{j=1}{f_j}=\sum{f}$. This form is useful for grouped data, where the $X_j$'s represent class marks and the $f_j$'s are the corresponding class frequencies.<p>
Occasionally the mean deviation is defined in terms of absolute deviations from the median or other average instead of from the mean. An interesting property of the sum $\sum^N_{j=1}\lvert X_j-a\rvert$ is that it is a minimum where $a$ is the median (i.e., the mean deviation about the median is a minimum).<p>
Note that it would be more appropriate to use the terminology _mean absolute deviation_ than _mean deviation_.

Below is a function that can be used to find the mean deviation. It is also found in the saved data file `Saves/mean_deviation.Rdata`.

In [5]:
md <- function(x) {
    return (sum(abs(x - mean(x)))/length(x))
}

---

__4.3.__ Find the mean deviation of the sets of numbers in problem 1.

### Solution
(a) The arithmetic mean is<p>
$$
\begin{align*}
\bar{X}=\frac{12+6+7+3+15+10_18+5}{8}=\frac{76}{8}=9.5
\end{align*}
$$
<p>
The mean deviation is<p>
$$
\begin{align*}
\text{MD}
=\frac{\lvert12-9.5\rvert+\lvert6-9.5\rvert+\lvert3-9.5\rvert+\lvert15-9.5\rvert+\lvert10-9.5\rvert+\lvert18-9.5\rvert+\lvert5-9.5\rvert}{8}
=\frac{2.5+3.5+2.5+6.5+5.5+0.5+8.5+4.5}{8}
=\frac{34}{8}=4.25
\end{align*}
$$
<p>
(b)
$$
\begin{align*}
\bar{X}=\frac{9+3+8+8+9+8+9+18}{8}=\frac{72}{8}=9
\end{align*}
$$
<p>
$$
\begin{align*}
\text{MD}
=\frac{\lvert9-9\rvert+\lvert3-9\rvert+\lvert8-9\rvert+\lvert8-9\rvert+\lvert9-9\rvert+\lvert8-9\rvert+\lvert9-9\rvert+\lvert18-9\rvert}{8}
=\frac{0+6+1+1+0+1+0+9}{8}=2.25
\end{align*}
$$
<p>
The mean deviation indicates that set (b) shows less dispersion than set (a), as it should.

In [6]:
p3.x <- c(12, 6, 7, 3, 15, 10, 18, 5)
p3.y <- c(9, 3, 8, 8, 9, 8, 9, 18)
(p4.MD.x <- md(p3.x))
(p4.MD.y <- md(p3.y))

[1] 4.25

[1] 2.25

---

__4.4.__ Find the mean deviation of the heights of the 100 male students at XYZ University.

In [7]:
Table_2.1

60-62,5
63-65,18
66-68,42
69-71,27
72-74,8


### Solution
From Problem 3.20, $\bar{X}=67.45$in. The work can be arranged as in This table:

In [8]:
p4.table <- matrix(c(61, 64, 67, 70, 73, 6.45, 3.45, 0.45, 2.55, 5.55, 5, 18, 42, 27, 8, 32.25, 62.10, 18.90, 68.85, 44.40), nrow=5)
rownames(p4.table) <- c("60-62", "63-65", "66-68", "69-71", "72-74")
colnames(p4.table) <- c("Class Mark (X)", "|X - \\bar{X}| = |X - 67.45|","Frequency (f)", "f|X - \\bar{X}|")
p4.table

,Class Mark (X),|X - \bar{X}| = |X - 67.45|,Frequency (f),f|X - \bar{X}|
60-62,61,6.45,5,32.25
63-65,64,3.45,18,62.10
66-68,67,0.45,42,18.90
69-71,70,2.55,27,68.85
72-74,73,5.55,8,44.40


$$
\begin{align*}
\text{MD}=\frac{\sum{f\lvert X-\bar{X}\rvert}}{N}=\frac{226.50}{100}=2.26\text{in}
\end{align*}
$$
<p>

In [9]:
p4.f <- number.of.students <- as.vector(Table_2.1)
p4.N <- sum(p4.f)
p4.X <- marks <- c(61, 64, 67, 70, 73)
p4.A <- guess <- 67
p4.d <- p4.X - p4.A
p4.X.bar <- p4.avg <- p4.A + sum(p4.f*p4.d)/p4.N
p4.dev <- abs(p4.X - p4.X.bar)
p4.fX <- p4.f*p4.dev
p4.table <- matrix(c(p4.X, p4.dev, p4.f, p4.fX), nrow=length(p4.X))
rownames(p4.table) <- rownames(Table_2.1)
colnames(p4.table) <- c("X", "|X-\\bar{X}|", "f", "f|X-\\bar{X}|")
p4.fX.sum <- sum(p4.fX)
(p4.MD.xyz <- signif(p4.fX.sum/p4.N, 4))
p4.MD.xyz <- 2.26
p4.boundaries <- c(59.5, 62.5, 65.5, 68.5, 71.5, 74.5)

[1] 2.265

---

__4.5.__ Determine the percentage of the students' heights in Problem 4 that fall within the ranges

(a) $\bar{X}\pm\text{MD}$

### Solution
The range from $65.29$ to $69.71$ in is $\bar{X}\pm\text{MD}=67.45\pm2.26$. This range includes all individuals in the third class $+\frac{1}{3}(65.5-65.19)$ of the students in the second class $+\frac{1}{3}(69.71-68.5)$ of the students in the fourth class (since the class-interval size is $3$in, the upper class boundary of the second class is $65.5$in, and the lower class boundary of the fourth class is $68.5$in). The number of students in the range $\bar{X}\pm\text{MD}$ is
<p>
$$
\begin{align*}
42+\frac{0.31}{3}(18)+\frac{1.21}{3}(27)=42+1.86+10.89=54.75\ \ \ \ \text{or}\ \ \ \ 55
\end{align*}
$$
<p>
    which is $55\%$ of the total.

In [10]:
p5.r1 <- round(range(p4.X.bar-p4.MD.xyz, p4.X.bar+p4.MD.xyz),2)
(round(p5.r1.pct <- 42 + (p4.boundaries[3]-p5.r1[1])/3*18 + (p5.r1[2]-p4.boundaries[4])/3*27,0))

[1] 55

(b) $\bar{X}\pm2\text{MD}$

### Solution
The range from $62.93$ to $71.97$ in is $\bar{X}\pm2\text{MD}=67.45\pm2(2.26)=67.45\pm4.52$. The number of students in the range $\bar{X}\pm2\text{MD}$ is
<p>
$$
\begin{align*}
18-\left(\frac{62.93-62.5}{3}\right)(18)+42+27+\left(\frac{71.97-71.5}{3}\right)(8)=85.67\ \ \ \ \text{or}\ \ \ \ 86
\end{align*}
$$
<p>
which is $86\%$

In [11]:
p5.r2 <- round(range(p4.X.bar-2*p4.MD.xyz, p4.X.bar+2*p4.MD.xyz),2)
(round(p5.r2.pct <- 18 - (p5.r2[1]-p4.boundaries[2])/3*18 + 42 + 27 + (p5.r2[2]-p4.boundaries[5])/3*8,0))

[1] 86

and (c) $\bar{X}\pm3\text{MD}$

### Solution
The range from $60.67$ to $74.23$ in is $\bar{X}\pm3\text{MD}=67.45\pm3(2.26)=67.45\pm6.78$. The number of students int he range $\bar{X}\pm3\text{MD}$ is<p>
$$
\begin{align*}
5-\left(\frac{60.67-59.5}{3}\right)(5)+18+42+27+\left(\frac{74.5-74.23}{3}\right)(8)=97.33\ \ \ \ \text{or}\ \ \ \ 97
\end{align*}
$$
    which is $97\%$ of the total.

In [12]:
p5.r3 <- round(range(p4.X.bar-3*p4.MD.xyz, p4.X.bar+3*p4.MD.xyz),2)
(round(p5.r3.pct <- 5 - (p5.r3[1] - p4.boundaries[1])/3*5 + 18 + 42 + 27 + (p4.boundaries[6] - p5.r3[2])/3*8,0))

[1] 91

---

## The Semi-Interquartile Range
The _semi-interquartile range_, or _quartile deviation_, of a set of data is denoted by $Q$ and is defined by<p>
\begin{align}
Q = \frac{Q_3 - Q_1}{2}\label{eq3}\tag{3}
\end{align}<p>
where $Q_1$ and $Q_3$ are the first and third quartiles for the data (see Problems 4.6 and 4.7). The interquartile range $Q_3-Q_1$ is sometimes used, but the semi-interquartile range is more common as a measure of dispersion.

---

__4.6.__ Find the semi-interquartile range for the height distribution of the students at XYZ University.

In [13]:
Table_2.1

60-62,5
63-65,18
66-68,42
69-71,27
72-74,8


### Solution
The lower and upper quartiles are $Q_1=65.5+\frac{2}{42}(3)=65.64$in and $Q_3=68.5+\frac{10}{27}(3)=69.61$in, respectively, and the semi-interquartile range (or quartile deviation) is $Q=\frac{1}{2}(Q_3-Q_1)=\frac{1}{2}(69.61-65.64)=1.98$in. Note that $50\%$ of the cases lie between $Q_1$ and $Q_3$ (i.e., $50$ students have heights between $65.64$ and $69.61$in).<p>
We can consider $\frac{1}{2}(Q_1+Q_3)=67.63$in to be a measure of central tendency (i.e., average height). It follwos that $50\%$ of the heights lie in the range $67.63\pm1.98$in.

In [14]:
p6.ci <- class.interval <- 3
p6.boundaries <- seq(59.5, 74.5, by=class.interval)
p6.cumsum <- cumsum(as.vector(Table_2.1))
p6.f.sum <- sum(Table_2.1)
p6.Q.breaks <- p6.f.sum/4

p6.Q1.index <- match(Table_2.1[p6.cumsum > p6.Q.breaks][1],Table_2.1)
p6.Q1.close.class <- p6.boundaries[p6.Q1.index]
p6.Q1.class <- as.vector(Table_2.1)[p6.Q1.index]
p6.Q1.remainder <- p6.Q.breaks - p6.cumsum[p6.Q1.index-1]
p6.Q1 <- round(p6.Q1.close.class + p6.Q1.remainder/p6.Q1.class*p6.ci,2)

p6.Q3.index <- match(Table_2.1[p6.cumsum > 3*p6.Q.breaks][1], Table_2.1)
p6.Q3.close.class <- p6.boundaries[p6.Q3.index]
p6.Q3.class <- as.vector(Table_2.1)[p6.Q3.index]
p6.Q3.remainder <- 3*p6.Q.breaks - p6.cumsum[p6.Q3.index-1]
p6.Q3 <- round(p6.Q3.close.class + p6.Q3.remainder/p6.Q3.class*p6.ci,2)

c((p6.Q.central <- round((p6.Q1 + p6.Q3)/2,2)), (p6.Q.pm <- round((p6.Q3 - p6.Q1)/2,2)))
(p6.Q.range <- c(p6.Q.central-p6.Q.pm, p6.Q.central+p6.Q.pm))

[1] 67.62  1.98

[1] 65.64 69.60

---

__4.7.__ Find the semi-interquartile range for the wages of the $65$ employees at the P&R Company in Table 2.6.

In [15]:
load("Saves/Table_2.6.Rdata")
Table_2.6

$250.00-$259.99,8
260.00-269.99,10
270.00-279.99,16
280.00-289.99,14
290.00-299.99,10
300.00-309.99,5
310.00-319.99,2


### Solution
From Problem 3.44, $Q_1=\$268.25$ and $Q_3=\$290.75$. Thus the semi-interquartile range $Q=\frac{1}{2}(Q_3-Q_1)=\frac{1}{2}(\$290.75-\$268.25)=\$11.25$. Since $\frac{1}{2}(Q_1+Q_3)=\$279.50$, we can conclude that $50\%$ of the employees earn wages lying in the range $\$279.50\pm\$11.25$.

In [16]:
p7.ci <- class.interval <- 10
p7.boundaries <- seq(249.995, 319.995, by=class.interval)
p7.cumsum <- cumsum(as.vector(Table_2.6))
p7.f.sum <- sum(Table_2.6)
p7.Q.breaks <- p7.f.sum/4

p7.Q1.index <- match(TRUE, p7.cumsum > p7.Q.breaks)[1]
p7.Q1.close.class <- p7.boundaries[p7.Q1.index]
p7.Q1.class <- as.vector(Table_2.6)[p7.Q1.index]
p7.Q1.remainder <- p7.Q.breaks - p7.cumsum[p7.Q1.index-1]
p7.Q1 <- round(p7.Q1.close.class + p7.Q1.remainder/p7.Q1.class*p7.ci,2)

p7.Q3.index <- match(TRUE, p7.cumsum > 3*p7.Q.breaks)[1]
p7.Q3.close.class <- p7.boundaries[p7.Q3.index]
p7.Q3.class <- as.vector(Table_2.6)[p7.Q3.index]
p7.Q3.remainder <- 3*p7.Q.breaks - p7.cumsum[p7.Q3.index-1]
p7.Q3 <- round(p7.Q3.close.class + p7.Q3.remainder/p7.Q3.class*p7.ci,2)

c((p7.Q.central <- round((p7.Q1 + p7.Q3)/2,2)), (p7.Q.pm <- round((p7.Q3 - p7.Q1)/2,2)))
(p7.Q.range <- c(p7.Q.central - p7.Q.pm, p7.Q.central + p7.Q.pm))

[1] 279.49  11.25

[1] 268.24 290.74

---

## The 10-90 Percentile Range
The $10$&mdash;$90$ _percentile range_ of a set of data is defined by<p>
\begin{align}
10-90\ \text{percentile range}=P_{90}-P_{10}\label{eq4}\tag{4}
\end{align}<p>
where $P_{10}$ and $P_{90}$ are the $10$th and $90$th percentiles for the data (see Problem 4.8). The semi-$10$&mdash;$90$ percentile range, $\frac{1}{2}(P_{90}-P_{10})$, can also be used but is not commonly employed.

---

__4.8.__ Find the $10$&mdash;$90$ percentile range of the heights of the students at XYZ University (Table 2.1).

In [17]:
Table_2.1

60-62,5
63-65,18
66-68,42
69-71,27
72-74,8


### Solution
Here $P_{10}=62.5+\frac{5}{18}(3)=63.33$in, and $P_{90}=68.5+\frac{25}{27}(3)=71.27in$. Thus the $10$&mdash;$90$ percentile range is $P_{90}-P_{10}=71.27-63.33=7.94$in. Since \frac{1}{2}(P_{10}+P_{90})=67.30$in and \frac{1}{2}(P_{90}-P_{10})=3.97$in, we can conclude that $80\%$ of the students have heights in the range $67.30\pm3.97$in.

In [18]:
p8.ci <- 3
p8.boundaries <- seq(59.5, 74.5, by=3)
p8.D.cumsum <- cumsum(as.vector(Table_2.1))
p8.f.sum <- sum(Table_2.1)
p8.D.breaks <- p8.f.sum/10

p8.D.10.index <- match(TRUE, p8.D.cumsum > p8.D.breaks)[1]
p8.D.10.close.class <- p8.boundaries[p8.D.10.index]
p8.D.10.class <- as.vector(Table_2.1)[p8.D.10.index]
p8.D.10.remainder <- p8.D.breaks - p8.D.cumsum[p8.D.10.index-1]
p8.D.10 <- round(p8.D.10.close.class + p8.D.10.remainder/p8.D.10.class*p8.ci,2)

p8.D.90.index <- match(TRUE, p8.D.cumsum > 9*p8.D.breaks)[1]
p8.D.90.close.class <- p8.boundaries[p8.D.90.index]
p8.D.90.class <- as.vector(Table_2.1)[p8.D.90.index]
p8.D.90.remainder <- 9*p8.D.breaks - p8.D.cumsum[p8.D.90.index-1]
p8.D.90 <- round(p8.D.90.close.class + p8.D.90.remainder/p8.D.90.class*p8.ci,2)

p8.D.90 - p8.D.10
c((p8.D.central <- round((p8.D.10 + p8.D.90)/2,2)), (p8.D.pm <- round((p8.D.90 - p8.D.10)/2,2)))
(p8.D.10.90.range <- c(p8.D.central - p8.D.pm, p8.D.central + p8.D.pm))

[1] 7.95

[1] 67.31  3.98

[1] 63.33 71.29