# Moments

In [1]:
moment <- function(X, r){
    return(sum(X^r)/length(X))
}

moment.about.mean <- function(X, r){
    return(sum((X-mean(X))^r)/length(X))
}

moment.about.A <- function(X, A, r){
    return(sum((X-A)^r)/length(X))
}

## Problem 5-1
Find the (a) first, (b) second, (c) third, and (d) fourth moments of the set $2, 3, 7, 8, 10$.

In [2]:
cat("Set: ",(p1.s <- c(2, 3, 7, 8, 10)), "\n")

Set:  2 3 7 8 10 


### Solution 5-1
(a) The first moment, or arithemtic mean, is

\begin{align}
\bar{X} = \frac{\sum{X}}{N}=\frac{2+3+7+8+10}{5}=\frac{30}{6}=6
\end{align}

(b) The second moment is

\begin{align}
\overline{X^2}=\frac{\sum{X^2}}{N}=\frac{2^2+3^2+7^2+8^2+10^2}{5}=\frac{226}{5}=45.2
\end{align}

(c) The third moment is

\begin{align}
\overline{X^3}=\frac{\sum{X^3}}{N}=\frac{2^3+3^3+7^3+8^3+10^3}{5}=\frac{1890}{5}=378
\end{align}

(d) The fourth moment is

\begin{align}
\overline{X^4}=\frac{\sum{X^4}}{N}=\frac{2^4+3^4+7^4+8^4+10^4}{5}=\frac{16594}{5}=3318.8
\end{align}

In [3]:
cat("First moment, or arithmetic mean: ", (p1.first.moment <- mean(p1.s)), "\n")
cat("Second moment:                    ", (p1.second.moment <- moment(p1.s, 2)), "\n")
cat("Third moment:                     ", (p1.third.moment <- moment(p1.s, 3)), "\n")
cat("Fourth moment:                    ", (p1.fourth.moment <- moment(p1.s, 4)), "\n")

First moment, or arithmetic mean:  6 
Second moment:                     45.2 
Third moment:                      378 
Fourth moment:                     3318.8 


---

## Problem 5-2
Find the (a) first, (b) second, (c) third, and (d) fourth moments about the mean for the set of numbers in [Problem 5.1](#Problem-5-1).

### Solution 5-2
(a)
\begin{align}
m_1 = \overline{(X-\bar{X})}=\frac{\sum{(X-\bar{X})}}{N}=\frac{(2-6)+(3-6)+(7-6)+(8-6)+(10-6)}{5}=\frac{0}{5}=0
\end{align}

$m_1$ is always equal to zero since $\overline{X-\bar{X}}=\bar{X}-\bar{X}=0$ (see [Problem 3.16](../../03%20Chapter%203%20The%20Mean,%20Median,%20Mode,%20and%20Other%20Measures%20of%20Central%20Tendency/02%20Solved%20Problems/03%20Properties%20of%20the%20arithmetic%20mean.ipynb#Problem-3-16)).

(b)
\begin{align}
m_2 = \overline{(X-\bar{X})^2}=\frac{\sum{(X-\bar{X})^2}}{N}=\frac{(2-6)^2+(3-6)^2+(3-6)^2+(7-6)^2+(8-6)^2+(10-6)^2}{5}=\frac{46}{5}=9.2
\end{align}

Note that $m_2$ is the variance $s^2$.

(c)
\begin{align}
m_3 = \overline{(X-\bar{X})^3}=\frac{\sum{(X-\bar{X})^3}}{N}=\frac{(2-6)^3+(3-6)^3+(3-6)^3+(7-6)^3+(8-6)^3+(10-6)^3}{5}=\frac{-18}{5}=-3.6
\end{align}

(d)
\begin{align}
m_4 = \overline{(X-\bar{X})^4}=\frac{\sum{(X-\bar{X})^4}}{N}=\frac{(2-6)^4+(3-6)^4+(3-6)^4+(7-6)^4+(8-6)^4+(10-6)^4}{5}=\frac{610}{5}=122
\end{align}

In [4]:
cat("First moment about the mean:            ", (p2.first.moment.mean <- moment.about.mean(p1.s, 1)), "\n")
cat("Second moment about the mean (variance):", (p2.second.moment.mean <- moment.about.mean(p1.s, 2)), "\n")
cat("Third moment about the mean:            ", (p2.third.moment.mean <- moment.about.mean(p1.s,  3)), "\n")
cat("Fourth moment about the mean:           ", (p2.fourth.moment.mean <- moment.about.mean(p1.s, 4)), "\n")

First moment about the mean:             0 
Second moment about the mean (variance): 9.2 
Third moment about the mean:             -3.6 
Fourth moment about the mean:            122 


---

## Problem 5-3
Find the (a) first, (b) second, (c) third, and (d) fourth moments about the origin 4 for the set of numbers in [Problem 5.1](#Problem_3_1).

### Solution 5-3
(a)
\begin{align}
m^\prime_1=\overline{(X-4)}=\frac{\sum{(N-4)}}{N}=\frac{(2-4)+(3-4)+(7-4)+(8-4)+(10-4)}{5}=2
\end{align}

(b)
\begin{align}
m^\prime_2=\overline{(X-4)^2}=\frac{\sum{(N-4)^2}}{N}=\frac{(2-4)^2+(3-4)^2+(7-4)^2+(8-4)^2+(10-4)^2}{5}=\frac{66}{5}=13.2
\end{align}

(c)
\begin{align}
m^\prime_3=\overline{(X-4)^3}=\frac{\sum{(N-4)^3}}{N}=\frac{(2-4)^3+(3-4)^3+(7-4)^3+(8-4)^3+(10-4)^3}{5}=\frac{298}{5}=59.6
\end{align}

(d)
\begin{align}
m^\prime_4=\overline{(X-4)^4}=\frac{\sum{(N-4)^4}}{N}=\frac{(2-4)^4+(3-4)^4+(7-4)^4+(8-4)^4+(10-4)^4}{5}=\frac{1650}{5}=330
\end{align}

In [5]:
cat("First moment about the origin 4:  ", (p3.first.moment.4 <- moment.about.A(p1.s,  4, 1)), "\n")
cat("Second moment about the origin 4: ", (p3.second.moment.4 <- moment.about.A(p1.s, 4, 2)), "\n")
cat("Third moment about the origin 4:  ", (p3.third.moment.4 <- moment.about.A(p1.s,  4, 3)), "\n")
cat("Fourth moment about the origin 4: ", (p3.fourth.moment.4 <- moment.about.A(p1.s, 4, 4)), "\n")

First moment about the origin 4:   2 
Second moment about the origin 4:  13.2 
Third moment about the origin 4:   59.6 
Fourth moment about the origin 4:  330 


---

## Problem 5-4
Using the results of Problems [5.2](#Problem-5-2) and [5.3](#Problem-4-3), verify the relations between the moments (a) $m_2=m^\prime_2-m^{\prime2}_1$, (b) $m_3=m^\prime_3-3m^\prime_1m^\prime_2+2m^{\prime3}_1$, and (c) $m_4=m^\prime_4-4m^\prime_1m^\prime_3+6m^{\prime2}_1m^\prime_2-3m^{\prime4}_1$.

### Solution 5-4
From [Problem 5.3](#Problem-5-3) we have $m^\prime_1=2$, $m^\prime_2=13.2$, $m^\prime_3=59.6$, and $m^\prime_4=330$. Thus:  
(a) $m_2=m^\prime_2-m^{\prime2}_1=13.2-(2)^2=13.2-4=9.2$  
(b) $m_3=m^\prime_3-3m^\prime_1m^\prime_2+2m^{\prime3}_1=59.6-(3)(2)(13.2)+2(2)^3=59.6-79.2+16=-3.6$  
(c) $m_4=m^\prime_4-4m^\prime_1m^\prime_3+6m^{\prime2}_1m^\prime_2-3m^{\prime4}_1=330-4(2)(59.6)+6(2)^2(13.2)-3(2)^4=122$  
in agreement with [Problem 5.2](#Problem-5-2)

In [6]:
cat("second moment: ", p3.second.moment.4 - p3.first.moment.4^2, "\n")
cat("third moment:  ", p3.third.moment.4  - 3*p3.first.moment.4*p3.second.moment.4 + 2*p3.first.moment.4^3, "\n")
cat("fourth moment: ", p3.fourth.moment.4 - 4*p3.first.moment.4*p3.third.moment.4  + 6*p3.first.moment.4^2*p3.second.moment.4 - 3*p3.first.moment.4^4, "\n")

second moment:  9.2 
third moment:   -3.6 
fourth moment:  122 


---

## Problem 5-5
Prove that $m_2=m^\prime_2-m^{\prime2}_1$, (b) $m_3=m^\prime_3-3m^\prime_1m^\prime_2+2m^{\prime3}_1$, and (c) $m_4=m^\prime_4-4m^\prime_1m^\prime_3+6m^{\prime2}_1m^\prime_2-3m^{\prime4}_1$.

### Solution 5-5
If $d=X-A$, then $X=A+d$, $\bar{X}=A+\bar{d}$, and $X-\bar{X}=d-\bar{d}$. Thus:

(a)
\begin{align}
m_2=\overline{(X-\bar{X})^2}=\overline{(d-\bar{d})^2}=\overline{d^2-2\bar{d}d+\bar{d}^2}
\end{align}
\begin{align}
=\bar{d^2}-2\bar{d}^2+\bar{d}^2=\overline{d^2}-\bar{d}^2=m^\prime_2-m^{\prime2}_1
\end{align}
(b)
\begin{align}
m_3=\overline{(X-\bar{X})^3}=\overline{(d-\bar{d})^3}=\overline{(d^3-3d^2\bar{d}+3d\bar{d}^2-\bar{d}^3)}
\end{align}
\begin{align}
=\overline{d^3}-3\bar{d}\overline{d^2}+3\bar{d}^3-\bar{d}^3=\overline{d^3}-3\bar{d}\overline{d^2}+2\bar{d}^3 = m^\prime_3-3m^\prime_1m^\prime_2+2m^{\prime3}_1
\end{align}
(c)
\begin{align}
m_4=\overline{(X-\bar{X})^4}=\overline{(d-\bar{d})^4}=\overline{(d^4-4d^3\bar{d}+6d^2\bar{d}^2-4d\bar{d}^3+\bar{d}^4)}
\end{align}
\begin{align}
=\overline{d^4}-4\bar{d}\overline{d^3}+6\bar{d}^2\overline{d^2}-4\bar{d}^4+\bar{d}^4=\overline{d^4}-4\bar{d}\overline{d^3}+6\bar{d}^2\overline{d^3}+6\bar{d}^2\overline{d^2}-3\bar{d}^4
\end{align}
\begin{align}
=m^\prime_4-4m^\prime_1m^\prime_3+6m^{\prime2}_1m^\prime_2-3m^{\prime4}_1
\end{align}  
By extension of this method, we can derive similar results for $m_5$, $m_6$, etc.